module.exports = {table : [{"Location":"Wayne Gretzky Dr North End Bridge SB","VDSID":"1001"},
{"Location":"Wayne Gretzky Dr North End Bridge NB","VDSID":"1002"},
{"Location":"Wayne Gretzky Dr South End Bridge SB","VDSID":"1003"},
{"Location":"Wayne Gretzky Dr South End Bridge NB","VDSID":"1004"},
{"Location":"Whitemud Dr - 164 St WB","VDSID":"1007"},
{"Location":"Whitemud Dr - 164 St EB","VDSID":"1008"},
{"Location":"Whitemud Dr - 178 St WB","VDSID":"1009"},
{"Location":"Whitemud Dr - 178 St EB","VDSID":"1010"},
{"Location":"James MacDonald Bridge - 101 St WB","VDSID":"1011"},
{"Location":"James MacDonald Bridge - 101 St EB","VDSID":"1012"},
{"Location":"94 Ave - Scona Rd NB","VDSID":"1013"},
{"Location":"Queen Eliz. Park Rd - N of Sask. Dr NB","VDSID":"1014"},
{"Location":"Queen Eliz. Park Rd - Queen. Eliz. Pool NB","VDSID":"1015"},
{"Location":"Whitemud Dr - 156 St WB","VDSID":"1016"},
{"Location":"Whitemud Dr - 156 St EB","VDSID":"1017"},
{"Location":"Whitemud Dr - 122 St WB","VDSID":"1018"},
{"Location":"Whitemud Dr - 122 St EB","VDSID":"1019"},
{"Location":"Yellowhead Tr - 62 St WB","VDSID":"1020"},
{"Location":"Yellowhead Tr - 62 St EB","VDSID":"1021"},
{"Location":"Yellowhead Tr - 121 St WB","VDSID":"1022"},
{"Location":"Yellowhead Tr - 131 St EB","VDSID":"1023"},
{"Location":"Yellowhead Tr - 163 St WB","VDSID":"1024"},
{"Location":"Yellowhead Tr - 163 St EB","VDSID":"1025"},
{"Location":"Whitemud Dr - Terwillegar Dr (E. Of) WB","VDSID":"1026"},
{"Location":"Whitemud Dr - Terwillegar Dr (E. Of) EB","VDSID":"1027"},
{"Location":"53 Ave - Whitemud Dr WB","VDSID":"1028"},
{"Location":"53 Ave - Whitemud Dr EB","VDSID":"1029"},
{"Location":"58A Ave - Whitemud Dr WB","VDSID":"1030"},
{"Location":"58A Ave - Whitemud Dr EB","VDSID":"1031"},
{"Location":"Whitemud Dr - Quesnell Br WB","VDSID":"1032"},
{"Location":"Whitemud Dr - Quesnell Br EB","VDSID":"1033"},
{"Location":"Whitemud Dr - 149 St (E. Of) WB","VDSID":"1034"},
{"Location":"Whitemud Dr - 149 St (E. Of) EB","VDSID":"1035"},
{"Location":"Whitemud Dr - 149 St (WB)","VDSID":"1036"},
{"Location":"Whitemud Dr - 149 St (EB)","VDSID":"1037"},
{"Location":"53 Ave - Whitemud Dr Offramp WB","VDSID":"1038"},
{"Location":"Terwillegar Dr - Whitemud Dr On Ramp WB","VDSID":"1039"},
{"Location":"53 Ave (N. Of) - Whitemud Dr On Ramp WB","VDSID":"1040"},
{"Location":"Whitemud Dr - Fox Dr Off Ramp WB","VDSID":"1041"},
{"Location":"Whitemud Dr - Fox Dr On Ramp WB","VDSID":"1042"},
{"Location":"Whitemud Dr - 149 St Off Ramp WB","VDSID":"1043"},
{"Location":"Whitemud Dr - 149 St On Ramp WB","VDSID":"1044"},
{"Location":"Whitemud Dr - 159 St Off Ramp WB","VDSID":"1045"},
{"Location":"Whitemud Dr - 159 St On Ramp WB","VDSID":"1046"}]}